# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uberpromocodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promos',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 19, 12, 47, 6, 444040, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
