# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberpromocodes', '0002_promos_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promos',
            name='validity',
            field=models.DateField(),
        ),
    ]
